name: Metrics
on:
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["main"] }
jobs:
  # github-metrics:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: lowlighter/metrics@latest
  #       with:
  #         token: ${{ secrets.METRICS_TOKEN }}
  #         plugin_traffic: yes
  #         plugin_lines: yes
  #         plugin_isocalendar: yes
  #         plugin_isocalendar_duration: half-year
  #         plugin_languages: yes
  #         plugin_languages_sections: most-used
  #         plugin_languages_limit: 8
  metrics:
    runs-on: ubuntu-latest
    name: generate-github-cards
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}
