name: Metrics
on:
    # Schedule daily updates
    schedule: [{cron: "0 0 * * *"}]
    # (optional) Run workflow manually
    workflow_dispatch:
    # (optional) Run workflow when pushing on master/main
    push: {branches: ["master", "main"]}
jobs:
    github-metrics:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - uses: lowlighter/metrics@latest
            with:
                token: ${{ secrets.METRICS_TOKEN }}
                plugin_traffic: yes
                plugin_lines: yes
                plugin_languages: yes
                plugin_languages_sections: most-used
                plugin_languages_recent_load: 400
                plugin_languages_recent_days: 30
                plugin_repositories: yes
                plugin_repositories_featured: j3lte/react-mustache-template-component, j3lte/debian-torproxy, j3lte/deno-soda
                plugin_people: yes
                plugin_people_types: followers, followed
                plugin_calendar: yes
                plugin_calendar_limit: 1
                plugin_activity: yes
                plugin_activity_limit: 5
                plugin_activity_days: 0
